# Generated by Django 6.0.2 on 2026-03-26 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('isin', models.CharField(blank=True, max_length=12, null=True)),
                ('face_value', models.DecimalField(decimal_places=2, default=1.0, max_digits=10)),
                ('market_cap', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('current_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('high_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('low_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('stock_pe', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('book_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('dividend_yield', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('roce', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('roe', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'companies',
                'indexes': [models.Index(fields=['symbol'], name='companies_symbol_66c09b_idx'), models.Index(fields=['name'], name='companies_name_c7a1b3_idx')],
            },
        ),
        migrations.CreateModel(
            name='FinancialPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_type', models.CharField(choices=[('Q', 'Quarterly'), ('A', 'Annual'), ('TTM', 'Trailing Twelve Months')], max_length=3)),
                ('period_date', models.DateField()),
                ('fiscal_year_end', models.DateField(blank=True, null=True)),
                ('period_name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'financial_periods',
                'indexes': [models.Index(fields=['period_type', 'period_date'], name='financial_p_period__4946e2_idx')],
                'unique_together': {('period_type', 'period_date')},
            },
        ),
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(max_length=50)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('data_version', models.CharField(blank=True, max_length=20, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_sources', to='stocks.company')),
            ],
            options={
                'db_table': 'data_sources',
                'unique_together': {('company', 'source_type')},
            },
        ),
        migrations.CreateModel(
            name='BalanceSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equity_capital', models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True)),
                ('reserves', models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True)),
                ('borrowings', models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True)),
                ('other_liabilities', models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True)),
                ('total_liabilities', models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True)),
                ('fixed_assets', models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True)),
                ('capital_work_in_progress', models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True)),
                ('investments', models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True)),
                ('other_assets', models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True)),
                ('total_assets', models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance_sheets', to='stocks.company')),
                ('period', models.ForeignKey(limit_choices_to={'period_type__in': ['A', 'Q']}, on_delete=django.db.models.deletion.CASCADE, to='stocks.financialperiod')),
            ],
            options={
                'db_table': 'balance_sheets',
                'ordering': ['-period__period_date'],
                'indexes': [models.Index(fields=['company', 'period'], name='balance_she_company_d00cbb_idx')],
                'unique_together': {('company', 'period')},
            },
        ),
        migrations.CreateModel(
            name='AnnualFinancial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales', models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True)),
                ('expenses', models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True)),
                ('operating_profit', models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True)),
                ('opm_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('other_income', models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True)),
                ('interest', models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True)),
                ('depreciation', models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True)),
                ('profit_before_tax', models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True)),
                ('tax_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('net_profit', models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True)),
                ('eps', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('dividend_payout_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annual_financials', to='stocks.company')),
                ('period', models.ForeignKey(limit_choices_to={'period_type': 'A'}, on_delete=django.db.models.deletion.CASCADE, to='stocks.financialperiod')),
            ],
            options={
                'db_table': 'annual_financials',
                'ordering': ['-period__period_date'],
                'indexes': [models.Index(fields=['company', 'period'], name='annual_fina_company_7fe22a_idx')],
                'unique_together': {('company', 'period')},
            },
        ),
        migrations.CreateModel(
            name='FinancialRatio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debtor_days', models.IntegerField(blank=True, null=True)),
                ('inventory_days', models.IntegerField(blank=True, null=True)),
                ('days_payable', models.IntegerField(blank=True, null=True)),
                ('cash_conversion_cycle', models.IntegerField(blank=True, null=True)),
                ('working_capital_days', models.IntegerField(blank=True, null=True)),
                ('roce_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_ratios', to='stocks.company')),
                ('period', models.ForeignKey(limit_choices_to={'period_type': 'A'}, on_delete=django.db.models.deletion.CASCADE, to='stocks.financialperiod')),
            ],
            options={
                'db_table': 'financial_ratios',
                'ordering': ['-period__period_date'],
                'unique_together': {('company', 'period')},
            },
        ),
        migrations.CreateModel(
            name='MovingAverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('ma_type', models.IntegerField(choices=[(50, '50 Day MA'), (200, '200 Day MA')])),
                ('value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moving_averages', to='stocks.company')),
            ],
            options={
                'db_table': 'moving_averages',
                'indexes': [models.Index(fields=['company', 'ma_type', 'date'], name='moving_aver_company_dbc8bc_idx')],
                'unique_together': {('company', 'date', 'ma_type')},
            },
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('volume', models.BigIntegerField(blank=True, null=True)),
                ('delivery_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='stocks.company')),
            ],
            options={
                'db_table': 'price_history',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['company', 'date'], name='price_histo_company_394cd3_idx')],
                'unique_together': {('company', 'date')},
            },
        ),
        migrations.CreateModel(
            name='QuarterlyFinancial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales', models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True)),
                ('expenses', models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True)),
                ('operating_profit', models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True)),
                ('opm_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('other_income', models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True)),
                ('interest', models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True)),
                ('depreciation', models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True)),
                ('profit_before_tax', models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True)),
                ('tax_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('net_profit', models.DecimalField(blank=True, decimal_places=0, max_digits=20, null=True)),
                ('eps', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quarterly_financials', to='stocks.company')),
                ('period', models.ForeignKey(limit_choices_to={'period_type': 'Q'}, on_delete=django.db.models.deletion.CASCADE, to='stocks.financialperiod')),
            ],
            options={
                'db_table': 'quarterly_financials',
                'ordering': ['-period__period_date'],
                'indexes': [models.Index(fields=['company', 'period'], name='quarterly_f_company_02bac7_idx')],
                'unique_together': {('company', 'period')},
            },
        ),
        migrations.CreateModel(
            name='ShareholdingPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promoters', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('fii', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('dii', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('government', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('public', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('number_of_shareholders', models.BigIntegerField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shareholding_patterns', to='stocks.company')),
                ('period', models.ForeignKey(limit_choices_to={'period_type': 'Q'}, on_delete=django.db.models.deletion.CASCADE, to='stocks.financialperiod')),
            ],
            options={
                'db_table': 'shareholding_patterns',
                'ordering': ['-period__period_date'],
                'indexes': [models.Index(fields=['company', 'period'], name='shareholdin_company_a07fc8_idx')],
                'unique_together': {('company', 'period')},
            },
        ),
    ]
