# Generated by Django 6.0.2 on 2026-03-26 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='symbol',
            field=models.CharField(db_index=True, max_length=200, unique=True),
        ),
    ]
